function satellites_generated = single_orbit_constellation(scenario, orbit_information, number_of_SATs, propagator, satellite_name)

SMA = orbit_information.SMA;
ecc = orbit_information.ecc;
inc = orbit_information.inc;
RAAN = orbit_information.RAAN;
AOP = orbit_information.AOP;
TA =  


satellites_generated = satellite(scenario,...
                               SMA * ones(number_of_SATs,1),...
                               ecc * ones(number_of_SATs,1),...
                               inc * ones(number_of_SATs,1),...
                               RAAN * ones(number_of_SATs,1),...
                               AOP * ones(number_of_SATs,1),...
                               TA,...
                               Name = satellite_name +"-" +(1:number_of_SATs), ...
                               OrbitPropagator = propagator);
 
end